name: Auto Merge Dependency Updates

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@233840bd5e3770d9e22c18d09c5427f70a860d51
        with:
          use-auto-merge: true
          allowed-actors: tjenkinson
