name: Auto Merge Dependency Updates

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@02539e1bf10c151577506a997cb9132459e662b9
        with:
          use-auto-merge: true
          allowed-actors: tjenkinson
