name: Auto Merge Dependency Updates

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@c56e60c495d06dae9e6fba7367895b9df9d53f8f
        with:
          use-auto-merge: true
          allowed-actors: tjenkinson
