name: Auto Merge Dependency Updates

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@728fd2c
        with:
          use-auto-merge: true
          allowed-actors: tjenkinson
